[project]
name = "torchreid"
authors = [
    {name = "Kaiyang Zhou"},
]
license = {file = "LICENSE"}
requires-python = ">=3.9"
version="1.4.1"
dependencies = [
    "numpy>=2.0.0, <3",
    "torch>=2.3.1, <3",
    "scipy",
    "pillow>=10.4.0, <11",
    "torchvision>=0.18.1, <1",
    "gdown",
]
readme = "README.rst"
description = "A library for deep learning person re-ID in PyTorch"
keywords = [
    'Person Re-Identification',
    'Deep Learning',
    'Computer Vision'
]

[build-system]
requires = [
    "cython>=3.0.10, <4",
    "numpy>=2.0.0, <3",
    "setuptools>=45",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project.urls]
"Homepage" = "https://kaiyangzhou.github.io"
"Bug Reports" = "https://github.com/KaiyangZhou/deep-person-reid/issues"
"Source" = "https://github.com/KaiyangZhou/deep-person-reid"

